[project]
name = "edu-data-architecture"
version = "0.1.0"
description = "Projeto de arquitetura de dados educacionais com modelagem OLTP e DW e pipeline ETL em Python."
authors = [
    {name = "IgorNatann", email = "Igornatan4@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sqlalchemy (>=2.0.49,<3.0.0)",
    "psycopg2-binary (>=2.9.12,<3.0.0)",
    "pydantic (>=2.13.3,<3.0.0)",
    "faker (>=40.15.0,<41.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)"
]

[tool.poetry]
package-mode = false


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
